# Generated by Django 2.1.5 on 2019-03-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
    ]
