# Generated by Django 2.1.5 on 2019-03-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsa',
            name='lab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bsa',
            name='requisite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
