# Generated by Django 2.1.5 on 2019-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190305_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_year_first_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='first_year_first_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='first_year_second_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='first_year_second_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='first_year_summer_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fourth_year_first_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fourth_year_first_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fourth_year_second_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fourth_year_second_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='second_year_first_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='second_year_first_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='second_year_second_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='second_year_second_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='second_year_summer_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='third_year_first_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='third_year_first_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='third_year_second_semester_bsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='third_year_second_semester_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
        ),
    ]
