# Generated by Django 2.1.5 on 2019-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190307_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourth_year_first_semester_bsn',
            name='descriptive_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='third_year_first_semester_bsn',
            name='descriptive_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='third_year_second_semester_bsn',
            name='descriptive_title',
            field=models.CharField(max_length=500),
        ),
    ]
