# Generated by Django 2.1.5 on 2019-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_forsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_year_first_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = First Year First Semester',
                'verbose_name_plural': 'BSBA = First Year First Semester',
            },
        ),
        migrations.CreateModel(
            name='first_year_second_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = First Year Second Semester',
                'verbose_name_plural': 'BSBA = First Year Second Semester',
            },
        ),
        migrations.CreateModel(
            name='fourth_year_first_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = Fourth Year First Semester',
                'verbose_name_plural': 'BSBA = Fourth Year First Semester',
            },
        ),
        migrations.CreateModel(
            name='fourth_year_second_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = Fourth Year Second Semester',
                'verbose_name_plural': 'BSBA = Fourth Year Second Semester',
            },
        ),
        migrations.CreateModel(
            name='second_year_first_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = Second Year First Semester',
                'verbose_name_plural': 'BSBA = Second Year First Semester',
            },
        ),
        migrations.CreateModel(
            name='second_year_second_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = Second Year Second Semester',
                'verbose_name_plural': 'BSBA = Second Year Second Semester',
            },
        ),
        migrations.CreateModel(
            name='third_year_second_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = Third Year Second Semester',
                'verbose_name_plural': 'BSBA = Third Year Second Semester',
            },
        ),
        migrations.CreateModel(
            name='tshird_year_first_semester_bsba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=100)),
                ('requisite', models.CharField(blank=True, max_length=100)),
                ('lab', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('no_of_units', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BSBA = Third Year First Semester',
                'verbose_name_plural': 'BSBA = Third Year First Semester',
            },
        ),
    ]
