# Generated by Django 2.1.5 on 2019-03-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_first_year_first_semester_bsba_first_year_second_semester_bsba_fourth_year_first_semester_bsba_fourt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tshird_year_first_semester_bsba',
            new_name='third_year_first_semester_bsba',
        ),
    ]
