# Generated by Django 2.1.5 on 2019-01-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
